common_args:
  training_type: "simulation"
  random_seed: 0

data_args:
  dataset: "mnist"
  data_cache_dir: ~/fedml_data
  partition_method: "hetero"
  partition_alpha: 0.5

model_args:
  model: "lr"

train_args:
  federated_optimizer: "Multi-HierFL"
  client_id_list: "[]"
  client_num_in_total: 1000
  client_num_per_round: 10
  comm_round: 10
  epochs: 5
  batch_size: 10
  client_optimizer: sgd
  learning_rate: 0.03
  weight_decay: 0.001
  group_method: "random"
  group_partition_type: "random"
  group_partition_file: "./group_partation.json"
  group_participation_method: "random"
  group_num: 10
  group_comm_round: 5
  federation_num : 5
  lr: 0.001

validation_args:
  frequency_of_the_test: 25

device_args:
  using_gpu: true
  gpu_id: 0

comm_args:
  backend: "sp"

tracking_args:
   # When running on MLOps platform(open.fedml.ai), the default log path is at ~/fedml-client/fedml/logs/ and ~/fedml-server/fedml/logs/
  enable_wandb: true
  wandb_key: 7afc5847eb7c7a114528be19d6950cc6cbb57a31
  wandb_entity: xta_fl
  wandb_project: simulation
  run_name: MHFLtest_5FL_10C_5G_5E_0.7Dis
  using_mlops: true