common_args:
  training_type: "cross_silo"
  using_mlops: false
  random_seed: 0

data_args:
  dataset: "cifar10"
  data_cache_dir: "../../../data/cifar10"
  partition_method: "hetero"
  partition_alpha: 0.5

model_args:
  model: "resnet56"
  model_file_cache_folder: "./model_file_cache" # will be filled by the server automatically
  global_model_file_path: "./model_file_cache/global_model.pt"

train_args:
  federated_optimizer: "FedAvg"
  client_id_list: "[1,2]"
  client_num_in_total: 2
  client_num_per_round: 2
  comm_round: 50
  epochs: 1
  batch_size: 10
  client_optimizer: sgd
  learning_rate: 0.001
  weight_decay: 0.001

validation_args:
  frequency_of_the_test: 5

device_args:
  worker_num: 2
  using_gpu: false
  # gpu_mapping_file: config/gpu_mapping.yaml
  # gpu_mapping_key: mapping_default

comm_args:
  backend: "GRPC"
  grpc_ipconfig_path: config/grpc_ipconfig.csv
  
tracking_args:
  log_file_dir: ./log
  local_log_output_path: ./log
  enable_wandb: false
  wandb_key: ee0b5f53d949c84cee7decbe7a619e63fb1f8408
  wandb_project: fedml
  wandb_name: fedml_torch_fedavg_mnist_lr


silo_args:
  nnode: 1
  node_rank: 0
  nproc_per_node: 5
  pg_master_address: '127.0.0.1'
  pg_master_port: 12345